In [32]:
import numpy as np
import pandas as pd

In [33]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [34]:
import pandas as pd
import numpy as np
import random

# Define the number of rows you want
num_rows = 1000

# Generate random data
data = {
    'Age': np.concatenate([
        np.random.randint(16, 59, size=int(num_rows * 0.8)),  # 80% of the ages between 16 and 58
        np.random.randint(1, 91, size=int(num_rows * 0.2))    # 20% of the ages between 1 and 90
    ]),
    'Gender': np.random.choice(['Male', 'Female'], size=num_rows),
    'Fever': np.random.uniform(98.0, 120.0, size=num_rows).round(1),
    'Cough': np.random.choice(['High', 'Low', 'Mild'], size=num_rows),
    'City': np.random.choice(['Delhi', 'Mumbai', 'Kolkata', 'Chennai', 'Bangalore', 'Hyderabad', 'Ahmedabad', 'Pune', 'Jaipur', 'Lucknow', 'Kanpur', 'Nagpur', 'Indore', 'Patna', 'Bhopal'], size=num_rows),
    'Has_Covid': np.random.choice(['Yes', 'No'], size=num_rows)
}

# Create DataFrame
df = pd.DataFrame(data)

# Save DataFrame to CSV
df.to_csv('covid_toy.csv', index=False)

print("CSV file 'covid_toy.csv' created successfully with random data.")


CSV file 'covid_toy.csv' created successfully with random data.


In [35]:
df = pd.read_csv('covid_toy.csv')

In [36]:
df.head(5)

Age  Gender  Fever Cough     City Has_Covid
0   21    Male  110.3  Mild   Bhopal       Yes
1   56  Female  111.3  High  Kolkata       Yes
2   53  Female  110.7   Low   Indore        No
3   44    Male   99.0  Mild    Delhi        No
4   44    Male  104.7  High   Nagpur       Yes

In [43]:
df['Cough'].value_counts()

Cough
Low     341
High    330
Mild    329
Name: count, dtype: int64

In [44]:
df['City'].value_counts()

City
Kolkata      85
Chennai      76
Jaipur       74
Patna        73
Nagpur       72
Kanpur       69
Delhi        66
Pune         65
Mumbai       64
Bhopal       63
Ahmedabad    62
Indore       60
Bangalore    59
Lucknow      58
Hyderabad    54
Name: count, dtype: int64

In [46]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=['Has_Covid']),df['Has_Covid'],test_size=0.2,random_state=42)

In [47]:
df.isnull().sum()

Age          0
Gender       0
Fever        0
Cough        0
City         0
Has_Covid    0
dtype: int64

In [49]:
#1.Aam Zindagi

In [54]:
s1 = SimpleImputer()
x_train_fevar = s1.fit_transform(x_train[['Fever']])

x_train_fever = s1.fit_transform(x_test[['Fever']])
x_train_fevar.shape

(800, 1)

In [57]:
from sklearn.preprocessing import OrdinalEncoder

# Ordinal encoding -- cough
oe = OrdinalEncoder(categories=[['High', 'Low', 'Mild']])
x_train_cough = oe.fit_transform(x_train[['Cough']])

# Also the test data
x_test_cough = oe.transform(x_test[['Cough']])

# Check the shape of the transformed training data
print(x_train_cough.shape)


(800, 1)


In [62]:
# Define the OneHotEncoder
one = OneHotEncoder(drop='first', sparse_output=False)

# Fit and transform the training data
x_train_gender_city = one.fit_transform(x_train[['Gender', 'City']])

# Transform the test data
x_test_gender_city = one.transform(x_test[['Gender', 'City']])

# Check the shape of the transformed training data
print(x_train_gender_city.shape)


(800, 15)


In [63]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Sample data
x_train = pd.DataFrame({
    'Gender': ['Male', 'Female', 'Transgender', 'Male', 'Female'],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Kolkata', 'Mumbai']
})
x_test = pd.DataFrame({
    'Gender': ['Female', 'Male', 'Transgender'],
    'City': ['Mumbai', 'Delhi', 'Kolkata']
})

# Define the OneHotEncoder
one = OneHotEncoder(drop='first', sparse_output=False)

# Fit and transform the training data
x_train_gender_city = one.fit_transform(x_train[['Gender', 'City']])

# Transform the test data
x_test_gender_city = one.transform(x_test[['Gender', 'City']])

# Check the shape of the transformed data
print("x_train_gender_city shape:", x_train_gender_city.shape)
print("x_test_gender_city shape:", x_test_gender_city.shape)

# Output the encoded data
print("x_train_gender_city:\n", x_train_gender_city)
print("x_test_gender_city:\n", x_test_gender_city)


x_train_gender_city shape: (5, 4)
x_test_gender_city shape: (3, 4)
x_train_gender_city:
 [[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 1. 0.]
 [0. 0. 0. 1.]]
x_test_gender_city:
 [[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 1. 0.]]
